sudo: required
services:
    - docker
git:
  depth: 1
  submodules: false
language: cpp
compiler: clang
env:
  global:
    FEELPP_STD_CPP=14

before_install:
- echo $TRAVIS_OS_NAME
- echo $HOME
- docker --version
- sudo apt-get update
- sudo apt-get install -y -q -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" docker-engine
- time docker pull feelpp/feelpp-env
- git clone --depth=1 https://github.com/feelpp/docker
- cd docker/dockerfiles/develop && docker build -f Dockerfile.dockerhub -t feelpp/develop:latest .

install:
- docker run feelpp/develop:latest true

script:
- true

