git:
  submodules: false
language: cpp
compiler:
  - clang
before_install:
  - sudo apt-get install clang-3.3 libboost1.48-all-dev libboost1.48-mpi-dev mpi-default-dev mpi-default-bin libeigen3-dev libcln-dev petsc-dev libxml2-dev gmsh bison flex doxygen doxygen-latex transfig imagemagick libtbb-dev libann-dev libglpk-dev
before_script:
  - mkdir opt && cd opt && ../configure -r
script:
  - make -j4
branches:
  only:
    - develop
