# force use of container based worker
sudo: false  
os: linux
git:
  depth: 1
  submodules: false

language: cpp
compiler: clang
# osx_image: xcode6.4

#- BUILD="llvm-3.7" FEELPP_CXX=clang++-3.7 FEELPP_CC=clang-3.7 BUILDTYPE=Release TARGET=quickstart CXXFLAGS="-O2 -DNDEBUG"
#- BUILD="gcc-5.1" FEELPP_CXX=g++-5.1 FEELPP_CC=gcc-5.1 BUILDTYPE=Release TARGET=quickstart CXXFLAGS="-O2 -DNDEBUG"

#- BUILD="g-debug" BUILDTYPE=Debug
#- BUILDTYPE=Release TARGET=tutorial

addons:
  apt:
    packages: &std_packages
    - gfortran
    - cmake
    - libtbb-dev
    - libopenmpi-dev
    - libglpk-dev
    - libxml2-dev
    - bison
    - flex
    - doxygen
    - imagemagick

matrix:
  include:
   - env: BUILD="llvm-3.5" COMPILER_VERSION="clang-3.5" FEELPP_CXX=clang++-3.5 FEELPP_CC=clang-3.5 BUILDTYPE=Release TARGET=quickstart CXXFLAGS="-O2 -DNDEBUG"
      addons: 
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.5
          packages:
            - *std_packages
            - clang-3.5
   - env: BUILD="llvm-3.6" COMPILER_VERSION="clang-3.6" FEELPP_CXX=clang++-3.6 FEELPP_CC=clang-3.6 BUILDTYPE=Release TARGET=quickstart CXXFLAGS="-O2 -DNDEBUG"
      addons: &clang36
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - *std_packages
            - clang-3.6
   - env: BUILD="llvm-3.7" COMPILER_VERSION="clang-3.7" FEELPP_CXX=clang++-3.7 FEELPP_CC=clang-3.7 BUILDTYPE=Release TARGET=quickstart CXXFLAGS="-O2 -DNDEBUG"
      addons: &clang37
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
          packages:
            - *std_packages
            - clang-3.7
   - env: BUILD="gcc-4.8" COMPILER_VERSION="g++-4.8" FEELPP_CXX=g++-4.8 FEELPP_CC=gcc-4.8 BUILDTYPE=Release TARGET=quickstart CXXFLAGS="-O2 -DNDEBUG"
      addons: &gcc48
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *std_packages
            - g++-4.8
   - env: BUILD="gcc-5" COMPILER_VERSION="g++-5" FEELPP_CXX=g++-5 FEELPP_CC=gcc-5 BUILDTYPE=Release TARGET=quickstart CXXFLAGS="-O2 -DNDEBUG"
      addons: &gcc5
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *std_packages
            - g++-5
  allow_failures:
  - os: osx
  - env: BUILD="gcc-4.8" COMPILER_VERSION="g++-4.8" FEELPP_CXX=g++-4.8 FEELPP_CC=gcc-4.8 BUILDTYPE=Release TARGET=quickstart CXXFLAGS="-O2 -DNDEBUG"
  - env: BUILD="gcc-5" COMPILER_VERSION="g++-5" FEELPP_CXX=g++-5 FEELPP_CC=gcc-5 BUILDTYPE=Release TARGET=quickstart CXXFLAGS="-O2 -DNDEBUG"

before_install:
  - echo $TRAVIS_OS_NAME
  - echo $HOME
  - if test "x$TRAVIS_OS_NAME" = "xlinux"; then apt-cache search clang; fi
  - if test "x$TRAVIS_OS_NAME" = "xlinux"; then export CXX=$FEELPP_CXX; fi
  - if test "x$TRAVIS_OS_NAME" = "xlinux"; then export CC=$FEELPP_CC; fi
 # - if test "x$TRAVIS_OS_NAME" = "xosx"; then cd /usr/local && git remote add feelpp https://github.com/feelpp/homebrew.git && git pull feelpp master; fi
 # - if test "x$TRAVIS_OS_NAME" = "xosx"; then brew tap feelpp/science; fi
  - if test "x$TRAVIS_OS_NAME" = "xosx"; then brew update; fi
  - if test "x$TRAVIS_OS_NAME" = "xosx"; then brew outdated xctool || brew upgrade xctool; fi
  - if test "x$TRAVIS_OS_NAME" = "xosx"; then brew install open-mpi; fi
#  - if test "x$TRAVIS_OS_NAME" = "xosx"; then brew tap homebrew/science; fi
  #- if test "x$TRAVIS_OS_NAME" = "xosx"; then brew install --only-dependencies feelpp; fi
  #install some submodules
  - git submodule update --init --recursive contrib/nlopt
  #- git submodule update --init --recursive contrib/nt2
  - git submodule update --init --recursive contrib/ipopt
  - git submodule update --init --recursive quickstart
  - export NPROCS=3
  - bash ports/travis/boost.sh; export BOOSTROOT=$HOME/software/install/boost; echo $BOOSTROOT
  - bash ports/travis/gmsh.sh; export GMSH_DIR=$HOME/software/install/gmsh-2.9.3; echo $GMSH_DIR
  - bash ports/travis/petsc.sh; export PETSC_DIR=$HOME/software/install/petsc-3.6.0; echo $PETSC_DIR
  - bash ports/travis/cln.sh; export CLN_DIR=$HOME/software/install/cln; echo $CLN_DIR

install:
- $CXX --version
- $CC --version
- mkdir opt-$BUILD && cd opt-$BUILD && ../configure --build=$BUILDTYPE -v --cxxflags="$CXXFLAGS"


script:
- make -j16 feelpp_ginac
- make -j1 feelpp
#- if ! test "x$TARGET" = "x"; then make $TARGET-check; fi

branches:
  only:
  - develop
  - master

cache:
  directories:
  - $HOME/software

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cf3f3fee0056f865adb2
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false


