git:
  depth: 1
  submodules: false

matrix:
  include:
      - env: TARGET_IMAGE="feelpp/feelpp-env:latest" TARGET_BRANCH="develop" CMAKE_FLAGS=""
        sudo: required
        services:
            - docker
      - env: TARGET_IMAGE="feelpp/feelpp-env:minimal" TARGET_BRANCH="feature/minimal" CMAKE_FLAGS="-DFEELPP_MINIMAL_BUILD=ON"
        sudo: required
        services:
            - docker

before_install:
- echo $TRAVIS_OS_NAME
- echo $HOME
- docker --version
- sudo apt-get update
- sudo apt-get install -y -q -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" docker-engine
- docker pull ${TARGET_IMAGE}
- git clone --depth=1 https://github.com/feelpp/docker
- cd docker/dockerfiles/develop && docker build -f Dockerfile.dockerhub -t ${TARGET_IMAGE} --build-arg=BRANCH=${TARGET_BRANCH} --build-arg=CMAKE_FLAGS="${CMAKE_FLAGS}" .

install:
- docker run feelpp/develop:latest true

script:
- true

