os:
  - linux
  - osx
git:
  submodules: false
language: cpp
compiler:
- clang
before_install:
- if test "x$TRAVIS_OS_NAME" = "xlinux"; then sudo add-apt-repository -y ppa:mapnik/boost-backports-1-54; fi
- if test "x$TRAVIS_OS_NAME" = "xlinux"; sudo add-apt-repository -y ppa:kalakris/eigen; fi
- if test "x$TRAVIS_OS_NAME" = "xlinux"; sudo apt-get -qq update; fi
- if test "x$TRAVIS_OS_NAME" = "xlinux"; sudo apt-get install -qq libboost1.54-all-dev mpi-default-dev mpi-default-bin libeigen3-dev
    libcln-dev petsc-dev libxml2-dev gmsh bison flex doxygen doxygen-latex transfig
    imagemagick libtbb-dev libann-dev libglpk-dev; fi
- if test "x$TRAVIS_OS_NAME" = "xosx"; then brew tap feelpp/science; fi
- if test "x$TRAVIS_OS_NAME" = "xosx"; then brew install --only-dependencies feelpp; fi
install:
- mkdir opt && cd opt && ../configure -r
script:
- make -j16 feelpp_ginac
- make -j2 feelpp
- make quickstart
- make tutorial
after_script: make check
branches:
  only:
  - develop
  - master
  - feature/explicit
cache:
- apt
notifications:
  email:
    recipients:
    - feelpp-devel@feelpp.org
    on_success: change
matrix:
  allow_failures:
  - gcc
