steps:
 - name: ':debian: testing,clang-3.9'
   command: tools/scripts/buildkite/install-feelpp-lib.sh
   env:
     CXX: clang++-3.9
     CC: clang-3.9
     JOBS: 20
     TARGET: debian:testing
 # - name: ':debian: sid,clang-4.0'
 #   command: tools/scripts/buildkite/install-feelpp-lib.sh
 #   env:
 #     JOBS: 20
 #     CXX: clang++-4.0
 #     CC: clang-4.0
 #     TARGET: debian:sid
 # - name: ':ubuntu: 16.10,gcc-6.2'
 #   command: tools/scripts/buildkite/install-feelpp-lib.sh
 #   env:
 #     JOBS: 20
 #     TARGET: ubuntu:16.10
 # - wait
 - wait
 - name: ':debian: testing,clang-3.9 :hammer: feelpp-base'
   command: tools/scripts/buildkite/install-feelpp.sh base
   env:
     CXX: clang++-3.9
     CC: clang-3.9
     JOBS: 20
     TARGET: debian:testing
 - wait
 - command: tools/scripts/buildkite/release.sh
   name: "Push images to :docker: Hub :rocket:"
   branches: develop
