steps:
 - trigger: "pkg-feelpp-focal"
   label: ":package: :ubuntu: focal Feel++ ${BUILDKITE_BRANCH}"
   async: true
   if: pipeline.slug=="feelpp" && ( build.branch == "develop" || build.branch == "master" )
 - wait
 - trigger: "pkg-feelpp-eoan"
   label: ":package: :ubuntu: eoan Feel++ ${BUILDKITE_BRANCH}"
   async: true
   if: pipeline.slug=="feelpp" && ( build.branch == "develop" || build.branch == "master" )   
 - wait
 - trigger: "pkg-feelpp-buster"
   label: ":package: :debian: buster Feel++  ${BUILDKITE_BRANCH}"
   async: true
   if: pipeline.slug=="feelpp" && ( build.branch == "develop" || build.branch == "master" )
notify:
  - slack: #pkg-feelpp   
