steps:
 - name: ':ubuntu: 16.10,clang-3.9 feelpp-testsuite :hammer:'
   command: tools/scripts/buildkite/install-feelpp.sh testsuite
   agents:
     docker: true
     ubuntu: "16.10"
   env:
     CXX: clang++-3.9
     CC: clang-3.9
     TARGET: ubuntu:16.10
 - wait
 - command: tools/scripts/buildkite/release.sh  -- feelpp-testsuite
   name: ":docker: push images to the hub :rocket:"
   agents:
     docker: true
     ubuntu: "16.10"
   env:
     TARGET: ubuntu:16.10
