steps:
 - name: ':$TARGET $CXX feelpp-testsuite :hammer:'
   command: feelpp/tools/scripts/buildkite/install-feelpp.sh testsuite
   agents:
     docker: true
     ubuntu: "16.04"
 - wait
 - command: feelpp/tools/scripts/buildkite/release.sh  -- feelpp-testsuite
   name: ":docker: push images to the hub :rocket:"
   agents:
     docker: true
     ubuntu: "16.04"
