steps:
 - name: ':feelpp: configure and build with default compiler'
   command: "tools/scripts/buildkite/install-feelpp-lib.sh"
   env:
     JOBS: 10
     TARGET: debian:sid     
 - name: ':feelpp: configure and build with clang 3.9'
   command: "tools/scripts/buildkite/install-feelpp-lib.sh"
   env:
     JOBS: 10   
     CXX: clang++-3.9
     CC: clang-3.9
     TARGET: debian:sid
