steps:
 - name: ':$TARGET, ${CXX}'
   command: feelpp/tools/scripts/buildkite/install-feelpp.sh feelpp
   agents:
     docker: true
     ubuntu: "16.04"
   artifact_paths: Testing/junit-*.xml
 - wait: ~
   continue_on_failure: false
 - plugins:
     junit-annotate#v1.6.0:
       artifacts: Testing/junit-*.xml
       fail-build-on-error: true
 - wait
 - command: feelpp/tools/scripts/buildkite/release.sh  -- feelpp
   name: ":docker: push images to the hub :rocket:"
   agents:
     docker: true
     ubuntu: "16.04"
 - wait
 - trigger: "feelpp-singularity"
   label: ":package: create feelpp :singularity: containers"
   async: true
   build:
     env:
       GIRDER_ID: "5a4fa90ab0e9571f842931e5"
       PROJECT: "feelpp"
       TAG: ${BUILDKITE_BRANCH}
 - trigger: "feelpp-testsuite"
   label: ":docker: compile and run the Feel++ testsuite :rocket:"
   async: true
   branches: "develop", "feature/sc-geomap"
   build:
    message: "${BUILDKITE_MESSAGE}"
    commit: "${BUILDKITE_COMMIT}"
    branch: "${BUILDKITE_BRANCH}"
 - name: ':$TARGET, $CXX, feelpp-toolboxes :hammer:'
   command: feelpp/tools/scripts/buildkite/install-feelpp.sh toolboxes
   agents:
     docker: true
     ubuntu: "16.04"
 - wait
 - command: feelpp/tools/scripts/buildkite/release.sh  -- feelpp-toolboxes
   name: ":docker: push images to the hub :rocket:"
   agents:
     docker: true
     ubuntu: "16.04"
 - wait
 - trigger: "feelpp-singularity"
   label: ":package: create feelpp :singularity: containers"
   async: true
   build:
     env:
       GIRDER_ID: "5a4fa90ab0e9571f842931e5"
       PROJECT: "feelpp-toolboxes"
       TAG: ${BUILDKITE_BRANCH}
 - name: ':$TARGET, $CXX, feelpp-mor :hammer:'
   command: feelpp/tools/scripts/buildkite/install-feelpp.sh mor
   agents:
     docker: true
     ubuntu: "16.04"
 - wait
 - command: feelpp/tools/scripts/buildkite/release.sh  -- feelpp-mor
   name: ":docker: push images to the hub :rocket:"
   agents:
     docker: true
     ubuntu: "16.04"
 - wait
 - trigger: "feelpp-singularity"
   label: ":package: create Feel++ :singularity: containers"
   async: true
   build:
     env:
       GIRDER_ID: "5a4fa90ab0e9571f842931e5"
       PROJECT: "feelpp-mor"
       TAG: ${BUILDKITE_BRANCH}
